server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:lmelgz/microservicecloud-config.git #会访问不到数据
           uri: https://github.com/lmelgz/microservicecloud-config.git #GitHub上面的git仓库名字
 
 

